/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./../components/BaseIcon/index.vue')['default']
    BaseTabbar: typeof import('./../components/BaseTabbar/index.vue')['default']
  }
}
